name: Latest Compatibility

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v9
        with:
          cache-dependency-glob: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv pip install --system nox

      - name: Run tests
        run: |
          nox -t latest
