name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[lint]"
          uv pip install --system nox

      - name: Run ruff
        run: |
          ruff check

      - name: Run mypy
        run: |
          mypy src

      - name: Run tests
        run: |
          nox --tag ci
